meta_product_name: "trainEQ"
meta_title: "trainEQ - feel all the feels"
meta_description: "Improve your emotional intelligence in online meetings. Recognize colleagues, clients, and students feelings with our innovative facial expression app."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
